- name: Installing Docker
  hosts: localhost
  become: yes
  vars:
    docker_compose_yaml: |
      services:
        sonarqube:
          image: sonarqube:community
          depends_on:
            - db
          environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
          volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
          ports:
            - "9000:9000"
        db:
          image: postgres:12
          environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
          volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
      volumes:
        sonarqube_data:
        sonarqube_extensions:
        sonarqube_logs:
        postgresql:
        postgresql_data:
  tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Uninstalling Previous Version of Docker (if any)
      apt:
        name: ['docker', 'docker.io', 'docker-client-latest', 'containerd', 'runc', 'docker-engine']
        state: absent

    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'htop', 'net-tools', 'vim', 'python3']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Installing docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']
        state: latest

    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Enabling docker service
      service:
        name: docker
        enabled: yes

    - name: Adding ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create directory /srv/sonarqube
      file:
        path: /srv/sonarqube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
    - name: Set vm.max_map_count in sysctl
      lineinfile:
        path: /etc/sysctl.conf
        line: 'vm.max_map_count=262144'
        regexp: '^vm.max_map_count='

    - name: Apply sysctl changes without reboot
      command: sysctl -p
      
    - name: Write Docker Compose file for SonarQube
      copy:
        dest: /srv/sonarqube/compose.yml
        content: "{{ docker_compose_yaml }}"
    - name: Run Docker Compose
      command: docker compose -f /srv/sonarqube/compose.yml up -d

    - name: Install required system packages
      apt: name=unzip state=latest update_cache=yes