variable "resource_group_name" {}
variable "automation_account_name" {}
variable "region" {}
variable "azure_blob_container_name" {}
variable "azure_blob_storage_endpoint" {}
variable "azure_database_admin_password" {}
variable "azure_database_admin_username" {}
variable "azure_database_names" {}
variable "azure_database_server_name" {}
variable "backup_retention_days" {}
variable "storage_account_name" {}
variable "azure_storage_key" {}
variable "role_assignment_scope" {}