subscription_id = "6e8e6b22-9037-4bd9-aa63-143e7b16e31c"
productName     =   "productdemo"
serviceName     =   "web"
serviceName1    =   "api"
env             =   "development" 
region          =   "australiaeast"

sqlAdminName    =   "sqladmin"
sqlAdminPassword=   ""
databaseName    =   "api"
databaseName1   =   "Hangfire"
